---

esphome:
  name: $name
  friendly_name: $friendly_name
  min_version: 2025.11.0

esp32:
  board: m5stack-atom
  framework:
    # Arduino framework has faster compilation but 
    # uses more RAM and Flash; ESP-IDF framework has 
    # slower compilation but uses less RAM and FLash
    type: esp-idf
    # type: arduino

# Specify pins used by the board to communicate over RS485
uart:
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 9600
  parity: EVEN

# Enable time component to reset energy at midnight
time:
  - platform: homeassistant
    id: homeassistant_time
